TestMVC/Models/ErrorViewModel.cs
using System;

namespace TestMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestMVC/Models/Site.cs
namespace TestMVC.Models
{
    public class Site
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public bool IsSecure { get; set; }
    }
}

TestMVC/Models/VM/SiteCreateModel.cs
namespace TestMVC.Models.VM
{
    public class SiteCreateModel
    {
        public string Name { get; set; }
        public string Url { get; set; }
        public bool IsSecure { get; set; }
    }
}

TestMVC/Models/VM/SiteEditModel.cs
namespace TestMVC.Models.VM
{
    public class SiteEditModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public bool IsSecure { get; set; }
    }
}

TestMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TestMVC.Models;

namespace TestMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestMVC/Controllers/SiteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using TestMVC.Context;
using TestMVC.Models;
using TestMVC.Models.VM;

namespace TestMVC.Controllers
{
    public class SiteController : Controller
    {
        private readonly TestMVCContext _context;
        public SiteController(TestMVCContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult All()
        {
            var sites = _context.Sites.ToList();
            return View(sites);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(SiteCreateModel siteCreateModel)
        {
            var site = new Site
            {
                IsSecure = siteCreateModel.IsSecure,
                Name = siteCreateModel.Name,
                Url = siteCreateModel.Url
            };

            _context.Sites.Add(site);
            _context.SaveChanges();

            TempData["success"] = $"Сайт {site.Name} успешно создан с ID {site.Id}";

            dynamic obj;
            obj = 1;
            obj = "1";
            return RedirectToAction("All");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var model = _context.Sites.FirstOrDefault(x => x.Id == Id);

            if (model == null)
                return RedirectToAction("All");

            var viewModel = new SiteEditModel
            {
                Id = model.Id,
                IsSecure = model.IsSecure,
                Url = model.Url,
                Name = model.Name
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(SiteEditModel editModel)
        {
            var model = _context.Sites.FirstOrDefault(x => x.Id == editModel.Id);

            if (model == null)
                return View(model);

            model.IsSecure = editModel.IsSecure;
            model.Name = editModel.Name;
            model.Url = editModel.Url;

            _context.Sites.Update(model);
            _context.SaveChanges();

            TempData["success"] = $"Сайт {model.Name} успешно изменен.";

            return RedirectToAction("All");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var site = _context.Sites.FirstOrDefault(x => x.Id == id);

            if (site == null)
            {
                TempData["error"] = $"Не удалось найти объект с ID: {id}";
                return RedirectToAction("All");
            }

            _context.Sites.Remove(site);
            _context.SaveChanges();

            TempData["success"] = $"Сайт {site.Name} успешно удален.";

            return RedirectToAction("All");
        }
    }
}

TestMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hello</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Site" asp-action="All">All Sites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Site" asp-action="Create">Create site</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TestMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TestMVC/Views/Site/All.cshtml
@using TestMVC.Models;
@{
    ViewData["Title"] = "Все записи";
}
@model List<Site>

<div>

    @if (TempData["success"] != null)
    {
        <h3 style="color: green">@TempData["success"]</h3>
    }

    @if (TempData["error"] != null)
    {
        <h3 style="color: red">@TempData["error"]</h3>
    }

    <table class="table">
        <thead>
            <tr>
                <td scope="col">SiteId</td>
                <td scope="col">SiteName</td>
                <td scope="col">SiteUrl</td>
                <td scope="col">IsSecure</td>
                <td scope="col">Action</td>
                <td scope="col">Action</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>
                    <a href="@item.Url">@item.Name</a>
                </td>
                <td>
                    @item.IsSecure
                </td>
                <td>
                    <a href="Edit/@item.Id" class="btn btn-outline-info">Изменить</a>
                </td>
                <td>
                    <a href="Delete/@item.Id" class="btn btn-outline-danger">Удалить</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

TestMVC/Views/Site/Create.cshtml
@using TestMVC.Models.VM

@{
    ViewData["Title"] = "Создать запись";
}

<form action="Create" method="post">
    <label class="form-label">Название сайта</label>
    <input type="text" name="Name" class="form-control" />

    <label>Url сайта</label>
    <input type="text" name="Url" class="form-control" />

    <label>Сайт не безопасный?</label>
    <input type="checkbox" name="IsSecure" />

    <button type="submit" class="btn btn-outline-success">Сохранить</button>
</form>

TestMVC/Views/Site/Edit.cshtml
@using TestMVC.Models.VM
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model SiteEditModel
<form action="Create" method="post">

    <input type="hidden" name="Id" value="@Model.Id" />
    <label>Название сайта</label>
    <input type="text" name="Name" value="@Model.Name" />

    <label>Url сайта</label>
    <input type="text" name="Url" value="@Model.Url" />

    <label>Сайт не безопасный?</label>
    @Html.CheckBoxFor(x => x.IsSecure)

    <button type="submit">Сохранить</button>
</form>